### ISSUE TITLE
Fix formatting of long import lists

### ISSUE THREAD

**Issue by tfausak** [commercialhaskell/hindent#242]
As suggested by @bergmark in https://github.com/chrisdone/hindent/issues/228#issuecomment-243302011.

**Comment by sgraf812** [comment]
In the same vein:
- Long lists of deriving
- Long lists of type class constraints
- Basically everything comma-separated which can overflow lines

**Comment by chrisdone** [comment]
Patches welcome on that -- there's still work to do on that and it's easier on those of us working on this when others take some of the gruntwork. 👍

**Comment by bergmark** [comment]
Thank you! 🎉
