### ISSUE TITLE
Record syntax (especially single constructor or single field cases)

### ISSUE THREAD

**Issue by sophie-h** [commercialhaskell/hindent#253]
If am suggesting the following change

```diff
-data X = X
-  { x :: Int
-  }
+data X
+  = X { x :: Int}
```

```diff
-data X = X
-  { x :: Int
-  } deriving (Show)
+data X
+  = X { x :: Int}
+  deriving (Show)
```

### Current record syntax

``` hs
data X = X
  { x :: Int
  }

data A
  = A { a :: Int}
  | A'
```

### Suggested record syntax

``` hs
data X
  = X { x :: Int}

data A
  = A { a :: Int}
  | A'
```

**Comment by chrisdone** [comment]
I think the
``` haskell
data B
  = B { b :: Int
      , b' :: Int}
  | B'
```
is a bug. The fields shouldn't depend on the length of the name `B`.

**Comment by qrilka** [comment]
@chrisdone what about the result I get using the current version and I suppose it was the same for at least half a year I remember using `hindent`:
```
data ABC
  = A { aField :: Int}
  | B { bField1 :: String
     ,  bField2 :: Int}
  | C
```
That comma gets placed under a space and 2 spaces get inserted between it and record name - does it deserve a separate issue maybe?

**Comment by sophie-h** [comment]
Some of the requested changes already happend. I did a cleanup to the issue description. Currently those aspects of data definitions are not covered by tests. But I added some via #395

**Comment by sophie-h** [comment]
@qrilka hope it was okay that I opened an issue for the change that you mentioned

**Comment by chrisdone** [comment]
Going with Kiril's issue, as the decision in hindent is never to depend on name lengths (anything else is a bug).
