### ISSUE TITLE
separate methods in type class instance declaration with new line

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/hindent#312]
Given the following type class:

``` haskell
class Bar x where
  doSomething :: x -> Int
  doSomethingElse :: x -> String
  oneMoreThing :: x
```

`hindent` currently formats instances like the following:

``` haskell
instance Bar Int where
  doSomething :: Int -> Int
  doSomething = id
  doSomethingElse :: Int -> String
  doSomethingElse = show
  oneMoreThing :: Int
  oneMoreThing = 0
```

However, this is slightly hard to read.  I think it would be nicer if it was formatted with newlines like this:

``` haskell
instance Bar Int where
  doSomething :: Int -> Int
  doSomething = id

  doSomethingElse :: Int -> String
  doSomethingElse = show

  oneMoreThing :: Int
  oneMoreThing = 0
```

The [styleguide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#blank-lines) has this to say about newlines in a type class instance declaration:

>  Add one blank line between functions in a type class instance declaration if the function bodies are large. Use your judgement.

`hindent` currently defaults to not adding blank lines.  I think `hindent` should default to adding blank lines.  This adds slightly more verbosity to the code, but it makes it much easier to read in most cases.

Ideally, there would be some sort of heuristic to tell whether or not there should be blank lines.  However, for now I think it would be simpler to just default to adding blank lines.

**Comment by cdepillabout** [comment]
This could also be handled with a similar kind of mechanism to #250.  If the programmer puts blank lines in by hand, then `hindent` preserves them.  If there are no blank lines, then `hindent` doesn't use blank lines.

**Comment by cdepillabout** [comment]
It looks like #200 is also doing something similar.

**Comment by chrisdone** [comment]
Closing for #379.
