### ISSUE TITLE
Misaligned comment at top of do-block

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/hindent#316]
```
long_function x = do
  -- bla
  let y = z
  return z
```

becomes

```
long_function x
              -- bla
 = do
  let y = z
  return z
```

Version `hindent 5.2.1`, built from current master.

---

**Update** at v5.2.2, c2ac3e3ce57c834525dc8ec5ca87d5e8d728b69b:

The output is now

```
long_function x
  -- bla
 = do
  let y = z
  return z

```

**Comment by cblp** [comment]
Looks like it is impossible with HSE. See also #338.

**Comment by pepeiborra** [comment]
And https://github.com/chrisdone/hindent/issues/220

**Comment by chrisdone** [comment]
Closing in favor of #511.
