### ISSUE TITLE
Misaligned haddocks on last constructor of data declaration

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/hindent#317]
```
data X
  = Y
    -- ^ bla1
  | Z
    -- ^ bla2
```

becomes

```
data X
  = Y
    -- ^ bla1
  | Z
-- ^ bla2
```

Using `hindent 5.2.1`.

**Comment by chrisdone** [comment]
This is a bit tricky to fix but there are solutions.

**Comment by sjakobi** [comment]
I can't reproduce this anymore at c2ac3e3ce57c834525dc8ec5ca87d5e8d728b69b.

Should I add a regression test?

**Comment by chrisdone** [comment]
Closing and ref'ing with #511.
