### ISSUE TITLE
No linebreaks for long functional dependency declarations

### ISSUE THREAD

**Issue by ivan-timokhin** [commercialhaskell/hindent#323]
In this code

``` haskell
class Foo a b c d e f | a b c d e -> f, a b c d f -> e, a b c e f -> d, a b d e f -> c, a c d e f -> b, b c d e f -> a where
  foo :: a -> b -> c -> d -> e -> f
```

first line is 124 characters long, but is left unchanged by hindent.  It should probably insert some line breaks.

Furthermore, if I linebreak the declaration manually, like this, for example:

``` haskell
class Foo a b c d e f
  | a b c d e -> f
  , a b c d f -> e
  , a b c e f -> d
  , a b d e f -> c
  , a c d e f -> b
  , b c d e f -> a
  where
  foo :: a -> b -> c -> d -> e -> f
```

hindent happily collapses the code to its original form, which not at all surprising, but mildly annoying.

**Comment by chrisdone** [comment]
Agreed.
