### ISSUE TITLE
RecursiveDo is enabled by default which steals `rec` as an identifier

### ISSUE THREAD

**Issue by MedeaMelana** [commercialhaskell/hindent#328]
hindent wouldn't format my code because I used `rec` as an identifier. GHC was happy, but hindent enables RecursiveDo by default which turns `rec` into a keyword.

**Comment by chrisdone** [comment]
I'll remove it. I think recursive do is not too common, and can be enabled with `-XRecursiveDo`.

**Comment by NorfairKing** [comment]
+1
