### ISSUE TITLE
Hindent produces unparsable promoted lists

### ISSUE THREAD

**Issue by emilaxelsson** [commercialhaskell/hindent#348]
This code

```haskell
a :: A '[ 'True ]
a = undefined
```

results in

```haskell
a :: A '['True]
a = undefined
```

which gives a parse error, presumably because `'['` looks like a character.

One workaround is to omit the tick on the promoted `True` constructor:

```haskell
a :: A '[True]
a = undefined
```

but this triggers a warning.

**Comment by aleator** [comment]
Also, if you have a (type-level) list of tuples, you need the tick. Ie. `'['(a,b,c,d)]`  fails to parse for the same reason as the above and `'[(a,b,c,d)]` means something else.

**Comment by sighingnow** [comment]
Close as fixed.
