### ISSUE TITLE
“{” is lost when formatting “Foo{}”

### ISSUE THREAD

**Issue by neongreen** [commercialhaskell/hindent#366]
Before `hindent`:

``` haskell
foo = Nothing{}
```

After `hindent`:

``` haskell
foo =
    Nothing
    }
```

(It might seem like a contrived example but I actually stumbled upon something similar at work.)

(Also, `foo Just{} = 0` works fine so it's only broken in expressions.)

**Comment by sighingnow** [comment]
It seems have already been fixed. Please update to the latest version of hindent. With hindent 5.2.2, you will get the following result:

~~~haskell
foo = Nothing {}
~~~
