### ISSUE TITLE
Consider breaking before the period following a quantification

### ISSUE THREAD

**Issue by expipiplus1** [commercialhaskell/hindent#371]
At the moment hindent produces 

```haskell
foobar
  :: forall a b c.
     Ord a
  => Something a b c -> [(a, b, c)]
```

however I think that this is slightly nicer to look at (and it reduces the length of the line with `forall` on by one character for free!)

```haskell
foobar
  :: forall a b c
   . Ord a
  => Something a b c -> [(a, b, c)]
```

**Comment by chrisdone** [comment]
I think both are fine and such probably going to leave the formatter as-is. People are _really_ touchy about modifications to type-signatures, so it's not likely to fly. :man_shrugging:
