### ISSUE TITLE
Always break before `::` on overlong signatures

### ISSUE THREAD

**Issue by expipiplus1** [commercialhaskell/hindent#390]
At the moment hindent does the following:

It replaces 

```haskell
someFunctionSignature :: With -> Enough -> (Arguments -> To ()) -> Overflow (The Line Limit)
```

with 

```haskell
someFunctionSignature :: With
                      -> Enough
                      -> (Arguments -> To ())
                      -> Overflow (The Line Limit)
```

It would remove the dependency on the length of `someFunctionSignature` if a break was put before the `::` to give

```haskell
someFunctionSignature 
  :: With
  -> Enough
  -> (Arguments -> To ())
  -> Overflow (The Line Limit)
```

For some other discussion see https://github.com/chrisdone/hindent/issues/284 and https://github.com/chrisdone/hindent/pull/288

It's a shame that this style seems to break some code highlighters, but I don't think that should impede this package's functionality.

**Comment by expipiplus1** [comment]
Interestingly for types with constraints hindent always breaks before the `::`, regardless of the length:

```haskell
fun :: Is => Short
```

goes to 

```haskell
fun
  :: Is
  => Short
```

**Comment by sighingnow** [comment]
I agree the idea that

~~~haskell
fun :: Is => Short
~~~

should be formatted as

~~~haskell
fun
  :: Is
  => Short
~~~

The behavior should keep consistent whether there exists typeclass constrains or not.

**Comment by expipiplus1** [comment]
I think single character functions with overlong signatures are very much an edge case, although I certainly agree that this

```haskell
f :: With
  -> Enough
  -> (Arguments -> To ())
  -> Overflow (The Line Limit)
```

looks slightly better than this 


```haskell
f 
  :: With
  -> Enough
  -> (Arguments -> To ())
  -> Overflow (The Line Limit)
```

-----------------

I do not agree that

```haskell
fun :: Is => Short
```

should be formatted as

```haskell
fun 
  :: Is
  => Short
```

unless the column limit is <= 18 as type signatures which fit entirely on one line should be broken only when the arguments have haddocks attached like

```haskell
fun
  :: Foo
  -- ^ Doc here
  -> Bar
```

-----------------

I agree when you say "I don't think it's a good way to always break when meets ::.". I'm proposing to not indent the types in the signature according to the length of the identifier, it goes very much against the formatting used for the rest of the Haskell syntax. My comment was just to highlight that the existing behaviour is different when constraints are present in a signature.

I do not have the privileges to reopen this issue, may you do so @sighingnow, please?

**Comment by sighingnow** [comment]
Close as fixed. Now the type signatures are formatted as

~~~haskell
fun :: Is => Short
fun = undefined

someFunctionSignature ::
     Wiiiiiiiiiiiiiiiiith
  -> Enough
  -> (Arguments -> To ())
  -> Overflow (The Line Limit)
~~~

The `::` in `someFunctionSignature` is placed in the same line for the compatibility with syntax highlighting of some text editors.

**Comment by expipiplus1** [comment]
Thanks very much for doing this!

I'm not convinced that it's hindent's job to be compromising, albeit only slightly, the tidiness of code to cope with poor editor support. For what it's worth, I much prefer the `::` to appear horizontally aligned with the arrows.
