### ISSUE TITLE
Code must distinguish HSE < 1.19 and >= 1.19

### ISSUE THREAD

**Issue by sophie-h** [commercialhaskell/hindent#396]
Because #278 is back with haskell-src-exts >= 1.19, the test locally fails for me.

See haskell-suite/haskell-src-exts#328 for upstream change.

**Comment by sophie-h** [comment]
Fixing the HSE version number for cabal would be an alternative.

**Comment by sighingnow** [comment]
Thanks for reporting upstream updates for us.
