### ISSUE TITLE
[Suggestion] way to recover extensibility

### ISSUE THREAD

**Issue by Javran** [commercialhaskell/hindent#399]
As all styles except `Johan-Tibell` have been dropped from hindent since `5.*`, this change makes hindent less extensible. I'm wondering if there is a way to recover the extensibility. I've read through some threads and try to understand the motivation behind this, so far what I've learnt is that:

- `Typeable` dynamic dispatching seems to significantly make the program slower 
- maintaining multiple styles is difficult

So now I'm thinking about a more `xmonad`-ish or `diagrams`-ish approach to this problem, that is, to expose main entry of the program and leave configuration as arguments.

I think by doing so, every user will have their own customized one configuration "to rule them all", without having to relying on `Typeable` to make any runtime decision. Also users will be able to have their own separated repo for their own styles so there won't be much custom style-related maintainance in `hindent` repo. And even if user want to use different styles across projects, they just build different binaries per style and ask their editor plugin to use that instead of the original one.

## few related threads & articles

this section is just for keeping a list so others don't have to spend time finding context.

- comments in https://github.com/commercialhaskell/hindent/commit/9a314533a7ad265a453123b0742981ddc549e86a
- #207
- [hindent 5: One style to rule them all](http://chrisdone.com/posts/hindent-5)

**Comment by chrisdone** [comment]
The other motivation was that in the grander scheme of things, style is mostly a childish concern that only matters in the degree of consistency. Eventually it'll be relegated to editor display settings like syntax highlighting but until then we waste cycles on not paying attention to the man behind the curtain.

**Comment by Javran** [comment]
@chrisdone thanks for the response! However I don't share some of your opinions and I was trying to avoid starting a discussion on that. It's just that I'm slightly upset about the fact that hindent is no longer as extensible as it used to be. There could be one universal Haskell style, but I don't think it hurts to open up the possibility for variations.

**Comment by NorfairKing** [comment]
> I don't think it hurts to open up the possibility for variations.
I do, and I think the disagreement on this topic was the reason to drop the other styles.

**Comment by sighingnow** [comment]
A complete configuration for Haskell's syntax will be complicate and hard to describe in common format (such as json or yaml). I think ordinary user won't have the motivation to make their own customized style configuration. Take the best practice and satisfy it as well as possible is the most efficient and practical approach for a  pretty printer, IMHO. Besides, it's not a easy job to refactor hindent for adapting complex user configuration.
