### ISSUE TITLE
Misplaced `where` with method comments

### ISSUE THREAD

**Issue by sheyll** [commercialhaskell/hindent#400]
I created a pull regression test in `TESTS.md` for this problem:

```haskell
class Foo a where
  -- Lala
  foo :: a
```

will be rendered as

```haskell
class Foo a 
  -- Lala
           where
  foo :: a
```

**Comment by sighingnow** [comment]
The root of this issue is the same with issue #220 and #316.

**Comment by sheyll** [comment]
Btw. the same happens for GADTs

**Comment by chrisdone** [comment]
Closing in favor of #511.
