### ISSUE TITLE
Hindent linebreaks after very short names if the total line length goes over 80, even if the result doesn't solve this problem.

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/hindent#405]
```
s "this is a very long string that goes over the line length"
```

gets reformatted to

```
s
    "this is a very long string that goes over the line length"
```

Which is even worse.

Hindent should only make this line break if the function's name is sufficiently long.

~~Maybe Hindent should also break up strings, but let that be a seperate issue.~~

**Comment by sighingnow** [comment]
I think in Haskell breaking up strings automatically for better pretty printing result is not an easy task.  For example, when breaking strings, could we breaking the words in the string ? And locale would also be a tough work when breaking up strings, IMPO.

Maybe it's the programmer's  responsibility to breaking long lines properly for better code layout.

**Comment by NorfairKing** [comment]
@sighingnow, as I said, let's let that be a seperate issue. The formatting is the subject of this issue.

**Comment by sighingnow** [comment]
Sorry for i didn't get your point just now, I have updated the label.

**Comment by NorfairKing** [comment]
Looks like this is fixed? Feel free to close.

**Comment by sighingnow** [comment]
Close as fixed (but not perfect). If anyone else have better suggestions please feel free to reopen.

**Comment by NorfairKing** [comment]
> When function's name is short, don't break line

I don't think this is necessarily the right approach.

I think it should be "If breaking a line makes for a greater violation of the maximum number of collumns, don't break the line."

**Comment by NorfairKing** [comment]
Also, is it possible that this is not done in `do` blocks?
