### ISSUE TITLE
Hindent breaks TH name captures of operators

### ISSUE THREAD

**Issue by utdemir** [commercialhaskell/hindent#412]
This one compiles without hindent:

```haskell
{-# LANGUAGE TemplateHaskell #-}

data T = (-)

q = '(-)
```

But hindent removes parens and the last line becomes `q = '-`, which gives `parse error on input ‘-’`.

Similar results with TypeOperators, this is also broken:

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeOperators #-}

data (-)

q = ''(-)
```

**Comment by sighingnow** [comment]
Thanks for reporting this bug, close as fixed.

**Comment by utdemir** [comment]
Thank you for the quick fix :)
