### ISSUE TITLE
Hindent can not parse empty case statements

### ISSUE THREAD

**Issue by utdemir** [commercialhaskell/hindent#414]
```haskell
{-# LANGUAGE EmptyCase #-}

f = case () of
```

Is syntactically valid, but Hindent gives `Parse error: EOF`.

Also, given `case () of {}`, hindent drops the `{}` and gives `case () of`, and if you try to hindent again, it gives parse error as previously demonstrated. 

I'm not sure if this is caused by `hindent` or `haskell-src-exts`.

**Comment by sighingnow** [comment]
Thanks for reporting this bug. The haskell-src-exts starts supporting `EmptyCase` extension since the version 1.19.0. I have updated the minimal version of HSE dependency in hindent to `1.19.0` and now this bug is fixed in HEAD.
