### ISSUE TITLE
Hindent breaks servant API's

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/hindent#417]
Hindent transforms this:

``` Haskell
type API = api1 :<|> api2
```
into this:

``` Haskell
type API = api1 (:<|>) api2
```

This breaks the build.

**Comment by sighingnow** [comment]
Thanks for your reporting this bug. It was introduced in 49033a5 mistakenly and get fixed now!

**Comment by NorfairKing** [comment]
Perfect, thanks for the quick fix!!
