### ISSUE TITLE
Missing support for unboxed tuples?

### ISSUE THREAD

**Issue by TerrorJack** [commercialhaskell/hindent#419]
Minimum example:

~~~
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE UnboxedTuples #-}

f :: (# Int, Int #) -> Int
f t = case t of
    (# x, _ #) -> x
~~~

`hindent-5.2.3` reports error on this. `hlint` recognizes it though, and they share a same version of `haskell-src-exts` in the same stackage nightly snapshot.

Does `hindent` already implement formatting unboxed tuples? Or am I missing anything here? Thanks!

**Comment by sighingnow** [comment]
You need enable the extension `UnboxedTuples` explicitly when format this code. Please try

~~~shell
hindent -XUnboxedTuples <your haskell  file>
~~~

Since the `#` symbol may conflict with the `#` operator in lens, we disable the extension `UnboxedTuples` designedly.

**Comment by TerrorJack** [comment]
@sighingnow Thanks for the remainder. With `hindent -XUnboxedTuples` it works indeed, however it formats patterns like `(# x, y #)` into `(#x, y#)`. After that `hindent` will fail to parse the formatted output.

**Comment by sighingnow** [comment]
Thanks for your reporting, the bug have been fixed now.

**Comment by sighingnow** [comment]
@TerrorJack sorry for close the this issue without pushing update to this repo yesterday. Please try with the latest code in master branch and this issue should be indeed fixed.
