### ISSUE TITLE
Hindent can no longer parse type applications code

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/hindent#426]
This got broken due to 

https://github.com/commercialhaskell/hindent/issues/421

in 

https://github.com/sighingnow/hindent/commit/fb50018618a6ad9f887819d3c7e229aa8e613b77

Both operators with `@` and type applications should be formattable.

**Comment by sighingnow** [comment]
Please try with

~~~shell
hindent -XTypeApplications <your haskell file>
~~~

**Comment by NorfairKing** [comment]
Can't hindent figure out that `TypeApplications` is turned on using the pragma's in the file?

**Comment by sighingnow** [comment]
Yes, we can't, IMHO.

In order to get pragmas from source file we need to parse the source file using HSE, but if we parse haskell source code without necessary extension flags (here is the `-XTypeApplications`) we would get nothing but a parse error, rather than partial result.

**Comment by NorfairKing** [comment]
GHC can do it, what's the actual limitation in HSE?

**Comment by NorfairKing** [comment]
I reject your objection.
See https://hackage.haskell.org/package/haskell-src-exts-1.19.1/docs/Language-Haskell-Exts.html#v:readExtensions
`readExtensions`.

**Comment by sighingnow** [comment]
Thanks, I will give a try as soon as possible.

**Comment by NorfairKing** [comment]
Thank you so much! I'm sorry for being harsh earlier :)

**Comment by sighingnow** [comment]
Now we can read the language extension pragmas from source code directly, without any command line argument.

@NorfairKing thanks for providing me the reference of function `readExtensions`.
