### ISSUE TITLE
Fully customisable .hindent.yaml

### ISSUE THREAD

**Issue by barischrooneyj** [commercialhaskell/hindent#427]
According to the README three options can be managed with a `.hindent.yaml` file:

 > The following fields are accepted and are the default:
> 
> ```
> indent-size: 2
> line-length: 80
> force-trailing-newline: true
> ```

It would be great if we could fully customise behaviour with a `.hindent.yaml` file :)

```
indent-size: 2
line-length: 80
force-trailing-newline: true
top-level-def-blank-lines: 2
type-sig-type-def-blank-lines: 1
binary-operator-whitespace: true
function-pragma: above
data-pragma: above
align-case-arrows: true
...
```

Many of these options are possibly already just variables used by hindent at runtime.

**Comment by NorfairKing** [comment]
+1

**Comment by NorfairKing** [comment]
-1: The less customisability the better. The entire point of automated formatters is to NOT have a discussion about style anymore.

**Comment by freckletonj** [comment]
@NorfairKing to me, the point of an automated formatter is to enforce _my_ style on _myself_ (or my team's style on us).

The influencers of `hindent` may have different projects that they optimize for, or simply different aesthetic mindsets.

**Comment by AshleyYakeley** [comment]
@freckletonj, you may be interested in this: http://chrisdone.com/posts/hindent-5

**Comment by chrisdone** [comment]
hindent won't be supporting more options than strictly necessary. line-length and indent-size are concessions, exceptions to the rule.
