### ISSUE TITLE
Brackets around type operator :*: are removed

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/hindent#428]
```haskell
{-# LANGUAGE TypeOperators #-}
import Control.Applicative

import GHC.Generics

value :: [(Maybe :*: Maybe) Int]
value = liftA2 (:*:) [Just 1] [Just 2]
```

This is valid (nonsensical) module, but hindent removes brackets around `:*:`, making it a type error.

**Comment by sighingnow** [comment]
Which version of hindent did you use?

**Comment by koterpillar** [comment]
hindent 5.2.3.

**Comment by sighingnow** [comment]
This bug seems have been fixed in #422. Could you try the HEAD version of hindent from github?

**Comment by koterpillar** [comment]
Confirming, `master` (0721221) works.

**Comment by sighingnow** [comment]
Thanks for your validation. This patch would be included in next release.
