### ISSUE TITLE
hindent fails on `#include`

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/hindent#430]
```
% cat include.hs 
#include "something-compat.h"

module Foo where

% cat include.hs| hindent
hindent: <interactive>: 3: 1: Parse error: module
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:62:21 in main:Main
```

Are `#include`s handled at all?

**Comment by phadej** [comment]
Maybe adding `#include` to https://github.com/commercialhaskell/hindent/blob/d43b1fd40b8054a7122705dd44efcb4f86b37416/src/HIndent.hs#L179
will fix the bug by splitting the source into two blocks with `#include` in between.

**Comment by sighingnow** [comment]
Put the `#include` pragma after the `module` line would work:

~~~haskell
module Foo where

#include "something-compat.h"
~~~

**Comment by sighingnow** [comment]
Seems an issue related to HSE, see https://github.com/haskell-suite/haskell-src-exts/issues/68
