### ISSUE TITLE
hindent breaks Haddocks for top-level-style comment of record field

### ISSUE THREAD

**Issue by gittywithexcitement** [commercialhaskell/hindent#435]
This is the code before hindent is run. When compiled with Haddock, it works.

``` hs
-- | Foo comment
data Foo =
  -- | Bar comment
  Bar
  {
  -- | baz comment
  baz :: Int  }
```

This is after hindent is run. This does not compile with Haddocks. The `-- | baz comment` has incorrectly been moved on the other side of the `{`. Haddocks complains about a parse error when it encounters the `{`.

```hs
-- | Foo comment
data Foo
  -- | Bar comment
      = Bar
  -- | baz comment
  { baz :: Int
  }
```

- As an additional issue of style, it's my opinion that `= Bar` should not be indented more than `{ baz :: Int`. If anything, `{ baz :: Int` should be indented more.

----

```
>hindent --version
hindent 5.2.2
```

**Comment by NorfairKing** [comment]
+1

**Comment by chrisdone** [comment]
Closing in favor of #511.
