### ISSUE TITLE
INLINE pragma for operators causes syntax error

### ISSUE THREAD

**Issue by DavidEichmann** [commercialhaskell/hindent#436]
`
$ echo "{-# INLINE (+++) #-}" | hindent
{-# INLINE +++ #-}
`

The parenthesis are removed which causes a syntax error.
hindent: 5.2.3
ghc: 8.0.2

**Comment by sighingnow** [comment]
This bug can't be reproduced with the latest version of Hindent so I'm going to close this issue. Feel free to reopen if you encounter any further trouble.
