### ISSUE TITLE
Feature Request: More Customization Options?

### ISSUE THREAD

**Issue by freckletonj** [commercialhaskell/hindent#437]
For example, I would like to be able to have `$` at the beginning of lines, instead of the end, or at least, have it preserve the current location.

I'm sure others may have other options that they'd like control over?

**Comment by NorfairKing** [comment]
Referencing #427.

**Comment by johnw42** [comment]
Probably not gonna happen. Check out this [blog post](http://chrisdone.com/posts/hindent-5).

**Comment by chrisdone** [comment]
No, this is not the aim of hindent. You can checkout brittany if you want options.
