### ISSUE TITLE
Enforce 4-space indents

### ISSUE THREAD

**Issue by AshleyYakeley** [commercialhaskell/hindent#440]
In the interests of creating a single common style, `hindent` should ignore the `indent-size` option and always use the most common indent size, which is [apparently 4](http://chrisdone.com/posts/hindent-5#fnref2).

**Comment by sighingnow** [comment]
Ping @chrisdone.

Considering Ashley's comment referred to your blog, what's your opinion about this proposal ?

**Comment by chrisdone** [comment]
The info on my blog wasn't accurate, I did a poll of the community
https://github.com/commercialhaskell/hindent/issues/236 updating the data
showed that hackage is more 50-50.

In the end there were 447 responses with 316 in favour of 2-space tabs.

The fact that --tab-width is supported is one (if not the only?) of the few
concessions made that without which people wouldn't be able to use Hindent
on projects without buy-in. Oddly that seems to be one of the few actual
style choices that projects tend to mandate...

My opinion is to leave the feature as-is.

**Comment by sighingnow** [comment]
According to response from @chrisdone. I'm going to close this issue and leave the feature as-is.
