### ISSUE TITLE
Feature request: turning it off for a fragment

### ISSUE THREAD

**Issue by michalrus** [commercialhaskell/hindent#442]
Like:

```haskell
x = 5
-- format: off
y = 6
-- format: on
z = 7
```

or similar.

Use case: Servant’s types. The API type would be most readable if each `:<|>` happened on a new line.

**Comment by sighingnow** [comment]
Hindent is just a pretty printer. I don't think we should make things become so complex for such a pretty printer.

**Comment by michalrus** [comment]
Considering:

* it’s a standalone binary
* which you can use to edit files in place (which happens by default, even without a CLI switch!)
* which means many people _will_ use it to auto-format whole projects regardless of which editors are used by their particular developers,

I can’t see why hindent it’s not a ~good~ perfect place to have this.

How do you suggest I should do automatic whole project auto-formatting, while keeping Servant types under control (i.e. not on a single 500-characters-long line)?

**Comment by michalrus** [comment]
Formatters for other languages have exactly this feature:

* `/* clang-format off */` in https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code
* `#[rustfmt_skip]` in https://github.com/rust-lang-nursery/rustfmt#tips
* `// format: off` in http://scalameta.org/scalafmt/#//format:off
* `// @formatter:off` in IntelliJ
* …

It feels necessary as a “safety valve”.

**Comment by NorfairKing** [comment]
+1
