### ISSUE TITLE
Q: What is the difference between the "operators, bad" and "operators, good" examples?

### ISSUE THREAD

**Issue by lpil** [commercialhaskell/hindent#444]
Hello!

Thanks for making this tool.

Looking at the [examples](https://github.com/commercialhaskell/hindent/blob/master/TESTS.md) there are "operators, bad" and "operators, good" examples. The "good" one looks more sensible to me, but when using hindent I get the "bad" example.

What is the difference between these two examples? The code appears to be semantically the same.

Cheers,
Louis

**Comment by chrisdone** [comment]
Bad in the sense that it should really just be two lines, but our algorithm is lacking and puts each operator on many lines after the first one.
