### ISSUE TITLE
Multiline `GHC.TypeLits.Symbol`s are being broken

### ISSUE THREAD

**Issue by michalrus** [commercialhaskell/hindent#451]
Reproduction:

```haskell
import GHC.TypeLits (Symbol)

data X (sym :: Symbol) deriving (Typeable)

type Y = X "abc\n\n\ndef"
```

will be formatted to:

```haskell
import GHC.TypeLits (Symbol)

data X (sym :: Symbol) deriving (Typeable)

type Y = X "abc


def"
```

Which is not correct Haskell and doesn’t compile. :crying_cat_face:

**Comment by michalrus** [comment]
Similarly for `\\`, and probably all escape sequences. :slightly_smiling_face:

**Comment by sighingnow** [comment]
Thanks for your report. I will check this problem as soon as possible.

**Comment by sighingnow** [comment]
Close as fixed.

**Comment by michalrus** [comment]
Thank you! Works as expected.
