### ISSUE TITLE
Hindent breaks case expressions

### ISSUE THREAD

**Issue by roehst** [commercialhaskell/hindent#454]
When I run hindent on

```
f =
  \x ->
    case x of
        Just 4 -> 4
        Nothing -> 4

```

I get this:
```

f =
  \x ->
    case x ofJust 4 -> 4
      Nothing -> 4
```

I run it on vim with :! hindent %.

How can I help diagnose?

**Comment by sighingnow** [comment]
Please try hindent 5.2.4.1.

**Comment by jligeza** [comment]
I have same issue and can't install the newest hindent, because:
```

**Comment by jligeza** [comment]
I have the same issue and can't install the newest hindent, because:
```
$  stack install hindent-5.2.4.1

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hindent-5.2.4.1:
    haskell-src-exts-1.18.2 must match >=1.19 (latest applicable is 1.19.1)
needed for unknown reason - stack invariant violated.

Plan construction failed.
```
How do I solve it?

**Comment by sighingnow** [comment]
What stack lts/nightly build plan did you use ?

**Comment by jligeza** [comment]
I am using the newest stack of `Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1` and the "build plan" is probably default of `lts-9.11`.

**Comment by power-fungus** [comment]
with hindent 5.2.4.1 (lts-10.5) and hindent 5.2.5 (nighly-2018-02-18), this does not happen on my machine.

**Comment by chrisdone** [comment]
Seems like this is an old bug.
