### ISSUE TITLE
Wrong type argument: listp, :group when applying hindent

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/hindent#468]
I'm using hindent through Spacemacs, and after a recent update `hindent-reformat-decl` and `hindent-reformat-buffer` stopped working with the error message:

```
Wrong type argument: listp, :group when applying hindent
```

When I change the following definition in `hindent.el`:

```
 (defcustom hindent-extra-args
   :group 'hindent
   :type 'sexp
   :safe #'listp)
 ```

into:

```
 (defcustom hindent-extra-args
   nil
   "dummy doc"
   :group 'hindent
   :type 'sexp
   :safe #'listp)
 ```

both functions start working again.

**Comment by koterpillar** [comment]
As a workaround, I put the following into `dotspacemacs/user-config`:

```
  (with-eval-after-load 'hindent
    (setq hindent-extra-args '()))
```

**Comment by PierreR** [comment]
Thanks ! I didn't believe the elisp could be broken so I have lost hours because of this issue ...
