### ISSUE TITLE
Release policy?

### ISSUE THREAD

**Issue by sophie-h** [commercialhaskell/hindent#475]
Would it be possible to introduce a release policy that is similar to PVP? Currently the formatting is changing between 5.2.X versions.

Also, 5.2.4 introduced a breaking change (#459) which is fixes but did not result in a point release. Also the current 5.2.4 stackage version will not build from scratch due to dependency incompatibility (#472), which is also fixed but not published as new version.

PVP would just be a question of using a policy. I think the other issues could also be addressed with relatively small effort, since patches were available almost instantaneously!

I think this would highly improve the usability of hindent!

**Comment by sighingnow** [comment]
Hindent 5.2.5 is available on hackage https://hackage.haskell.org/package/hindent-5.2.5 .

**Comment by chrisdone** [comment]
We do try to bump the major version if code formatting changes.
