### ISSUE TITLE
Hindent produces invalid Syntax from FFI exports

### ISSUE THREAD

**Issue by schroffl** [commercialhaskell/hindent#479]
Given this line of source code:
```haskell
foreign export ccall "test" test :: IO ()
```

Hindent (`hindent 5.2.4.1`) produces this output:
```haskell
foreign export ccall Just "test" test :: IO ()
```
As you can see, a  `Just` was added in front of the exported function name, which obviously results in a parse error when running ghc.

**Comment by sighingnow** [comment]
Close as fixed.
