### ISSUE TITLE
Quotes are dropped from package imports

### ISSUE THREAD

**Issue by cdsmith** [commercialhaskell/hindent#480]
Consider this input:

    {-# LANGUAGE PackageImports #-}
    import qualified "base" Prelude as P

Running hindent changes it to:

    {-# LANGUAGE PackageImports #-}
    import qualified base Prelude as P

which is a syntax error.

**Comment by sighingnow** [comment]
Thanks for your report, fixed now.

**Comment by joneshf** [comment]
Is it possible to get a new version with the fix?

**Comment by joneshf** [comment]
@sighingnow Any update on a release?
