### ISSUE TITLE
"Unexpected end of input while lexing quasi-quoter" error

### ISSUE THREAD

**Issue by chrishaig14** [commercialhaskell/hindent#491]
A very basic test like this fails
`echo 'y = [x|x<-[1..10]]' | hindent`
```
hindent: <interactive>: 1: 5: Unexpected end of input while lexing quasi-quoter
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:62:21 in main:Main
```
If I put a space before the pipe in the list comprehension, it works just fine:
`echo 'y = [x |x<-[1..10]]' | hindent`
`y = [x | x <- [1 .. 10]]`

But, of course, I would like it to add all missing spaces. At first, since I'm new to Haskell I thought that probably it was just absolutely necessary to have a space before the pipe, but `y = [x|x<-[1..10]]` works ok.

**Comment by chrisdone** [comment]
It's not possible to support it without the space. hindent will put a space in there anyway.
