### ISSUE TITLE
hindent.el does not work with bird-style literate Haskell

### ISSUE THREAD

**Issue by raxod502** [commercialhaskell/hindent#496]
Consider the following text in `test.lhs`:

```
Every expression in Haskell has a type which is determined at compile
time. All the types composed together by function application have to
match up. If they don't, the program will be rejected by the
compiler. Types become not only a form of guarantee, but a language
for expressing the construction of programs.
```

Running `emacs -Q`, I load the latest revisions of `haskell-mode` (d71cca7f5ddc8178f5fe331563edcefe91cc0bcb) and `hindent.el` (6f6db40cca1b759f78d7e4b971111e40833c3aa0), run `M-x hindent-mode`, and press `M-q` with point at the beginning of the fifth line (beginning with `for`). Result:

```
hindent-reformat-region-as-is: hindent: <interactive>:1:33: Parse error: of
```

This seems to me like a bug.

**Comment by chrisdone** [comment]
hindent doesn't support literate haskell.

**Comment by raxod502** [comment]
Really? It looks like https://github.com/commercialhaskell/hindent/pull/111 explicitly _added_ support.

**Comment by chrisdone** [comment]
Oh, that. I think that only applies to code with a prefix (such as `> ` or `    `). It's not quite literate haskell support.

**Comment by raxod502** [comment]
But according to https://github.com/commercialhaskell/hindent/issues/103#issuecomment-78647883,

> `hindent` attempts to guess the boundaries of the declaration being edited, and only sends that to `haskell-src-exts`.

Thus I think https://github.com/commercialhaskell/hindent/issues/103 should make this work, if only `hindent.el` would refrain from trying to indent the code when you're not in a code block.
