### ISSUE TITLE
Build fails with Cabal 2.2.0.1

### ISSUE THREAD

**Issue by HJvT** [commercialhaskell/hindent#500]
Using GHC 8.4.2, `cabal install hindent` fails with:
<pre>
[1 of 4] Compiling HIndent.CabalFile ( src\HIndent\CabalFile.hs, dist\dist-sandbox-eb001579\build\HIndent\CabalFile.o )

src\HIndent\CabalFile.hs:11:1: error:
    Could not find module `Distribution.PackageDescription.Parse'
    Perhaps you meant
      Distribution.PackageDescription.Parsec (from Cabal-2.2.0.1)
      Distribution.PackageDescription.Check (from Cabal-2.2.0.1)
      Distribution.PackageDescription.Quirks (from Cabal-2.2.0.1)
    Use -v to see a list of the files searched for.
   |
11 | import Distribution.PackageDescription.Parse
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</pre>

**Comment by chrisdone** [comment]
PR merged.
