### ISSUE TITLE
`hindent` takes exponential time to pretty print

### ISSUE THREAD

**Issue by facundominguez** [commercialhaskell/hindent#531]
## Problem

`hindent` takes exponential time when printing the following program.

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

Input haskell
```haskell
f = f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f(f f))))))))))))))))))))))))))
```

```
$ hindent --version
hindent 5.2.7

$ time hindent test.hs

real	2m45.051s
user	2m44.136s
sys	0m0.913s
```

**Comment by chrisdone** [comment]
That's true. Do you have a real world use-case of this?

**Comment by facundominguez** [comment]
I don't, I just discovered this while studying `hindent`.

**Comment by chrisdone** [comment]
Oki doki!
